# game_data.py

# --- 1. 基礎資料定義 (時空王時間表) ---
GAP_BOSS_SCHEDULE = {
    0: [9, 23],    # 週一
    1: [13, 23],   # 週二
    2: [17, 23],   # 週三
    3: [9, 21],    # 週四
    4: [11],       # 週五
    5: [1, 15],    # 週六
    6: [19]        # 週日
}
WEEKDAY_NAMES = ["週一", "週二", "週三", "週四", "週五", "週六", "週日"]

# --- 2. 抽卡池資料 (2026/03/09 最新完整機率更新) ---
gacha_items = [
    # 傳說
    {"name": "深夜的回應", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "黃金沙漠之夢", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "日暮的閃光", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "嚎哭的太陽", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "純白的帝王", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "鐵血的勝利者", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "鬥爭的品格", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "強敵的鬥志", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "時間的沙塵暴", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "極夜游行", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "極夜進攻", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "盛夏祝福", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "寬容統治", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "純白的氣息", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "扭曲的天意", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "忠誠不渝", "rarity": "傳說", "rate": 0.000003, "image": ""},
    {"name": "仲夏夜之夢", "rarity": "傳說", "rate": 0.000004, "image": ""},
    {"name": "黃金田野之歌", "rarity": "傳說", "rate": 0.000004, "image": ""},
    {"name": "迎月心願", "rarity": "傳說", "rate": 0.000004, "image": ""},
    {"name": "神聖之夜的審判", "rarity": "傳說", "rate": 0.000004, "image": ""},
    {"name": "崇高光輝", "rarity": "傳說", "rate": 0.000004, "image": ""},
    {"name": "斬擊騎士", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "先知者的光輝", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "冬季森林的流浪者", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "鋼鐵監視者", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "朗多的榮耀", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "高貴的義務", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "永遠的正義", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "卓越的美德", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "富貴的寵兒", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "星群的誓約", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "光耀飛翔", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "猛將威嚴", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "星浪散步", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "深化的羈絆", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "滿月律令", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "白夜的衝鋒者", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "寧靜之夜的祝福", "rarity": "傳說", "rate": 0.000008, "image": ""},
    {"name": "基爾伯特的驕傲", "rarity": "傳說", "rate": 0.000012, "image": ""},
    {"name": "奧多的冷酷", "rarity": "傳說", "rate": 0.000012, "image": ""},
    {"name": "卡巴洛克的意志", "rarity": "傳說", "rate": 0.000012, "image": ""},
    {"name": "梅迪亞的大義", "rarity": "傳說", "rate": 0.000012, "image": ""},
    {"name": "王國名譽", "rarity": "傳說", "rate": 0.000012, "image": ""},
    {"name": "夏夜極光", "rarity": "傳說", "rate": 0.000012, "image": ""},
    {"name": "極夜的追擊者", "rarity": "傳說", "rate": 0.000012, "image": ""},
    {"name": "席捲而來的敵意", "rarity": "傳說", "rate": 0.000012, "image": ""},

    # 英雄
    {"name": "自由的旗幟", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "被遺忘的英雄鎧甲", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "抵抗之風", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "被遺忘的守護誓約", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "名將的風采", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "猶達斯的品格", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "不屈的鬥魂", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "處決者的劍光", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "片刻閒暇", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "波光假期", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "鋼鐵信仰", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "冬日慶典的傳令", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "初雪的特使", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "禁忌的魔力", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "船長的紀律", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "水晶湖渡假客", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "豐饒的結實", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "嚴冬的溫暖", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "堅定的決斷", "rarity": "英雄", "rate": 0.000026, "image": ""},
    {"name": "繼承者祈願", "rarity": "英雄", "rate": 0.000053, "image": ""},
    {"name": "劍士的決心", "rarity": "英雄", "rate": 0.000053, "image": ""},
    {"name": "湖之翼", "rarity": "英雄", "rate": 0.000053, "image": ""},
    {"name": "孤獨的修行", "rarity": "英雄", "rate": 0.000053, "image": ""},
    {"name": "藝術的感覺", "rarity": "英雄", "rate": 0.000053, "image": ""},
    {"name": "大海的敬酒", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "古王國的滅亡", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "賢者的權威", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "貝涅特的直覺", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "帕爾媞雅的魅惑", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "絕倫者的榮譽", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "亥斯特的雅量", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "議員的資格", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "烈士的氣魄", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "隱藏的實力", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "隱密的重擊", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "戰場鬃毛", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "鐵匠的火花", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "盛夏悠閒", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "完美假期", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "月光大海旋律", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "珊瑚色避暑客", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "滿月的歸鄉", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "大雪的回憶", "rarity": "英雄", "rate": 0.000054, "image": ""},
    {"name": "荊棘祈願", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "傳承的智慧", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "完全忠誠", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "深淵中的傲慢", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "服從的特權", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "塔拉普的氣勢", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "恩人的庇護", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "金光野心", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "金光主宰", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "謀略家的術策", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "探索者的革新", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "船長的秩序", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "中秋之夜", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "雪花精靈的童話", "rarity": "英雄", "rate": 0.000081, "image": ""},
    {"name": "殘酷的宣告", "rarity": "英雄", "rate": 0.000081, "image": ""},

    # 稀有
    {"name": "塔拉普儀式服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "羽毛筆研究服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "卡希米爾聯盟制服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "幻象聯隊軍服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "堅決之心", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "西吉爾詩袍", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "克隆船員服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "火翼鎧甲", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "烏鴉迷彩服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "波拉西亞傳令服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "金獅會泳裝", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "草花蛇泳裝", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "口哨冒險服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "害羞的雪人", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "調皮的雪人", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "冷漠的雪人", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "黃色鯊魚裝", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "褐色福兔", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "藍色悸動樹", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "先鋒隊潛入服", "rarity": "稀有", "rate": 0.000208, "image": ""},
    {"name": "幻象聯隊特戰服", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "黯墓人追悼服", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "征服知識之塔", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "金獅會外出服", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "護衛兵盔甲", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "新諾德深淵服", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "西吉爾戰鬥服", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "歌唱之鎚", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "西吉爾抵抗軍騎士服", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "探勘隊泳裝", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "波拉西亞泳裝", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "雲岩壁探險服", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "日暮冒險服", "rarity": "稀有", "rate": 0.000416, "image": ""},
    {"name": "橘色鯊魚裝", "rarity": "稀有", "rate": 0.000417, "image": ""},
    {"name": "綠色鯊魚裝", "rarity": "稀有", "rate": 0.000417, "image": ""},
    {"name": "深褐色福兔", "rarity": "稀有", "rate": 0.000417, "image": ""},
    {"name": "黃色閃亮樹", "rarity": "稀有", "rate": 0.000417, "image": ""},
    {"name": "盪浪者初行服", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "迷霧護衛裝", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "波拉西亞商人服", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "迷霧護衛戰鬥服", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "黃昏野戰服", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "纏結工團工作服", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "霞光泳裝", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "星濤探險服", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "藍色鯊魚裝", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "白色福兔", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "灰色福兔", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "綠色慶典樹", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "白色心願樹", "rarity": "稀有", "rate": 0.000626, "image": ""},
    {"name": "先鋒隊訓練服", "rarity": "稀有", "rate": 0.000626, "image": ""},

    # 高級
    {"name": "朗多傳令服", "rarity": "高級", "rate": 0.004145, "image": ""},
    {"name": "地蜘蛛便服", "rarity": "高級", "rate": 0.004145, "image": ""},
    {"name": "自衛隊盔甲", "rarity": "高級", "rate": 0.004145, "image": ""},
    {"name": "卡希米爾聯盟書記服", "rarity": "高級", "rate": 0.004145, "image": ""},
    {"name": "托培爾便服", "rarity": "高級", "rate": 0.004145, "image": ""},
    {"name": "波拉西亞探索服", "rarity": "高級", "rate": 0.004145, "image": ""},
    {"name": "阿明塔探險服", "rarity": "高級", "rate": 0.008291, "image": ""},
    {"name": "波拉西亞旅行服", "rarity": "高級", "rate": 0.008291, "image": ""},
    {"name": "旅人護身服", "rarity": "高級", "rate": 0.008292, "image": ""},
    {"name": "纏結工團助手服", "rarity": "高級", "rate": 0.008292, "image": ""},
    {"name": "自由傭兵團盔甲", "rarity": "高級", "rate": 0.008292, "image": ""},
    {"name": "阿明塔流浪服", "rarity": "高級", "rate": 0.008292, "image": ""},
    {"name": "深色樹叢採集服", "rarity": "高級", "rate": 0.008292, "image": ""},
    {"name": "紅錨船員服", "rarity": "高級", "rate": 0.008292, "image": ""},
    {"name": "石牙象防寒服", "rarity": "高級", "rate": 0.008292, "image": ""},
    {"name": "自由航海士制服", "rarity": "高級", "rate": 0.012438, "image": ""},
    {"name": "暗月外出服", "rarity": "高級", "rate": 0.012438, "image": ""},
    {"name": "紡織工見習服", "rarity": "高級", "rate": 0.012438, "image": ""},
    {"name": "白夜手行商服", "rarity": "高級", "rate": 0.012438, "image": ""},
    {"name": "藍風鎖子甲", "rarity": "高級", "rate": 0.012438, "image": ""},
    {"name": "絎縫盔甲", "rarity": "高級", "rate": 0.012438, "image": ""},
    {"name": "地蜘蛛鎧甲", "rarity": "高級", "rate": 0.012438, "image": ""},
    {"name": "藍結鎧甲", "rarity": "高級", "rate": 0.012438, "image": ""},

    # 一般
    {"name": "殘兵的生鏽重甲", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "殘兵破舊制服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "殘兵的破碎長袍", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "殘兵的破爛輕甲", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "殘兵的破碎隱身服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "殘兵的毀損馬甲", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "萊茵索夫便服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "老舊的探險服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "破舊自衛隊服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "簡陋的護身服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "繼承的航海服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "破爛出遊服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "破爛的傳令服", "rarity": "一般", "rate": 0.055550, "image": ""},
    {"name": "古老旅行服", "rarity": "一般", "rate": 0.055550, "image": ""},
]

# --- 3. 抽卡輔助資料 (這段也移過來) ---
item_names = [item['name'] for item in gacha_items]
item_rates = [item['rate'] for item in gacha_items]
item_map = {item['name']: item for item in gacha_items}